import { Role } from './game.model';

// Role distribution table: totalPlayers -> role counts
export const ROLE_DISTRIBUTION: Record<number, Record<Role, number>> = {
  4:  { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 0, WITNESS: 0, INVESTIGATOR: 2 },
  5:  { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 0, WITNESS: 0, INVESTIGATOR: 3 },
  6:  { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 1, WITNESS: 1, INVESTIGATOR: 2 },
  7:  { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 1, WITNESS: 1, INVESTIGATOR: 3 },
  8:  { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 1, WITNESS: 1, INVESTIGATOR: 4 },
  9:  { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 1, WITNESS: 1, INVESTIGATOR: 5 },
  10: { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 1, WITNESS: 1, INVESTIGATOR: 6 },
  11: { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 1, WITNESS: 1, INVESTIGATOR: 7 },
  12: { FORENSIC: 1, MURDERER: 1, ACCOMPLICE: 1, WITNESS: 1, INVESTIGATOR: 8 },
};

// Timer defaults (in seconds)
export const TIMERS = {
  NIGHT_DISCUSSION: 60,
  NIGHT_CARD_SELECTION: 30,
  FORENSIC_MARKER: 60,
  DISCUSSION_ROUND_1: 240,
  DISCUSSION_ROUND_2: 180,
  DISCUSSION_ROUND_3: 120,
  WITNESS_HUNT: 300,
  EVENT_RULED_OUT: 30,
} as const;

// Card counts
export const CARD_COUNTS = {
  MEANS_TOTAL: 48,
  CLUES_TOTAL: 48,
  CARDS_PER_PLAYER: 4,
  LOCATION_TILES: 30,
  CAUSE_TILES: 30,
  CLUE_TILES: 60,
  EVENT_CARDS: 6,
  CLUE_TILES_PER_ROUND: 4,
} as const;

// Player limits
export const PLAYER_LIMITS = {
  MIN: 4,
  MAX: 12,
} as const;
